// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package resdata

import "fyne.io/fyne/v2"

var resourceAuthors = &fyne.StaticResource{
	StaticName: "AUTHORS",
	StaticContent: []byte(
		"Serhii Rudenko <sr@ios.in.ua>"),
}
