version: 2
project_name: kube_switch
builds:
  -
    builder: zig
    targets:
      - x86_64-linux-gnu
    env:
      - CGO_ENABLED=1
      - CC=zig cc
      - CXX=zig c++
      - GOFLAGS = -mod=vendor
      - GO111MODULE = auto
      - GIT_OWNER = redacid

    flags:
      #-L/usr/include
      #-L/usr/lib/x86_64-linux-gnu

checksum:
  name_template: 'CHECKSUMS'

snapshot:
  version_template: "{{ .Tag }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'