version: 2
project_name: kube-switch
builds:
  - main: ./
    env:
      - CGO_ENABLED=0
      - GOFLAGS = -mod=vendor
      - GO111MODULE = on
      - GIT_OWNER = redacid
    goos:
      #- windows
      - linux
      #- darwin
    goarch:
      #- "386"
      - amd64
      #- arm
      #- arm64
    goamd64:
      - v1
    flags:
      - -trimpath
      - -tags=netgo
      - -a
      - -v
    ldflags:
      - -extldflags "-static"
      - -X main.version={{.Tag}}
    ignore:
      - goos: darwin
      - goos: windows
      - goarch: arm
      - goarch: arm64
      - goarch: "386"
      - go386:
          - sse2
          - hardfloat
      - goarm:
          - 6
          - 7
      - goppc64:
          - power8
          - power9
      - goriscv64:
          - rva22u64

checksum:
  name_template: 'CHECKSUMS'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'