version: 2
project_name: kube-switch
builds:
  - main: ./
    targets:
      - linux_amd64_v1
    env:
      - CGO_ENABLED=1
      - CC=zig cc
      - GOFLAGS = -mod=vendor
      - GO111MODULE = auto
      - GIT_OWNER = redacid
#    goos:
#      - linux
#    goarch:
#      - amd64
#    goamd64:
#      - v1
    flags:
      - -trimpath
      - -tags=netgo
      - -a
      - -v
    ldflags:
      - -extldflags "-static"
      - -X main.version={{.Tag}}
      #- -L /usr/include/
#    ignore:
#      - goos: linux
#        goarch:
#          - "386"
#          - arm
#          - arm64
#      - goos: darwin
#        goarch:
#          - "386"
#          - arm
#          - arm64
#          - amd64
#      - goos: windows
#        goarch:
#          - arm
#          - arm64
#          - "386"
#          - amd64
#      - go386:
#          - sse2
#          - hardfloat
#      - goarm:
#          - 6
#          - 7
#      - goppc64:
#          - power8
#          - power9
#      - goriscv64:
#          - rva22u64

checksum:
  name_template: 'CHECKSUMS'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'