apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: asdasdasd
      server: https://asdasdasdasdasdasdasd.yl4.eu-central-1.eks.amazonaws.com
    name: arn:aws:eks:eu-central-1:1234567890:cluster/test-aws-kuber
  - cluster:
      certificate-authority-data: asdasdasd
      server: https://asdasdasdasdasdasdasd.gr7.eu-west-1.eks.amazonaws.com
    name: arn:aws:eks:eu-west-1:0987654321:cluster/nonprod-aws-kuber
  - cluster:
      certificate-authority-data: asdasdasd
      server: https://asdasdasdasdasdasdasd.gr7.eu-west-1.eks.amazonaws.com
    name: arn:aws:eks:eu-west-1:0987654321:cluster/prod-aws-kuber
contexts:
  - context:
      cluster: arn:aws:eks:eu-central-1:1234567890:cluster/test-aws-kuber
      user: arn:aws:eks:eu-central-1:1234567890:cluster/test-aws-kuber
    name: test-aws-kuber
  - context:
      cluster: arn:aws:eks:eu-west-1:0987654321:cluster/nonprod-aws-kuber-122
      user: arn:aws:eks:eu-west-1:0987654321:cluster/nonprod-aws-kuber
    name: nonprod-aws-kuber
  - context:
      cluster: arn:aws:eks:eu-west-1:0987654321:cluster/production-aws-kuber-cbd3
      user: arn:aws:eks:eu-west-1:0987654321:cluster/prod-aws-kuber
    name: prod-aws-kuber
current-context: test-aws-kuber
kind: Config
preferences: {}
users:
  - name: arn:aws:eks:eu-central-1:1234567890:cluster/test-aws-kuber
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - --region
          - eu-central-1
          - eks
          - get-token
          - --cluster-name
          - test-aws-kuber
          - --output
          - json
        command: aws
        env:
          - name: AWS_PROFILE
            value: "1234567890"
        interactiveMode: IfAvailable
        provideClusterInfo: false
  - name: arn:aws:eks:eu-west-1:0987654321:cluster/nonprod-aws-kuber
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - --region
          - eu-west-1
          - eks
          - get-token
          - --cluster-name
          - nonprod-aws-kuber
          - --output
          - json
        command: aws
        env:
          - name: AWS_PROFILE
            value: "0987654321"
        interactiveMode: IfAvailable
        provideClusterInfo: false
  - name: arn:aws:eks:eu-west-1:0987654321:cluster/prod-aws-kuber
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - --region
          - eu-west-1
          - eks
          - get-token
          - --cluster-name
          - prod-aws-kuber
          - --output
          - json
        command: aws
        env:
          - name: AWS_PROFILE
            value: "0987654321"
        interactiveMode: IfAvailable
        provideClusterInfo: false
